language: ruby
rvm:
  - 2.0.0-p451
  - 2.1.5
  - 2.2.0
notifications:
  slack:
    secure: efaVBjnWEeRXeVv0w0tU0CMJwjpdH5UkNrOutW3rrIPsMaiZVvweZs9pUBUrtl74e3d54OFaY3ziSXehKJPwp2c3DmOjrFiPQrJ0d0nYD/yUGxbcQsDdaWZ9yCK+lXzP1DZFemTksTHa8BZmt0M+V6V9QEU+T4JzYwbUljhLBDo=
